input_boolean:
  farbzyklus_akustikpaneel:
    name: Farbzyklus Akustikpaneel
    icon: mdi:palette

automation:
  - alias: Akustikpaneel Farbwechsel
    description: Wechselt das Licht zwischen zufälligen kräftigen Farben
    triggers:
      - trigger: state
        entity_id: input_boolean.farbzyklus_akustikpaneel
        to: "on"
      - trigger: time_pattern
        seconds: "/10"
    condition:
      - condition: state
        entity_id: input_boolean.farbzyklus_akustikpaneel
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id:
            - light.akustikpaneel_seite_rgbw_light_0
            - light.akustikpaneel_oben_rgbw_light_0
        data:
          rgbw_color: >
            {% set colors = [
              [255, 0, 0],     
              [255, 127, 0],   
              [255, 255, 0],   
              [127, 255, 0],   
              [0, 255, 0],     
              [0, 255, 127],   
              [0, 255, 255],   
              [0, 127, 255],   
              [0, 0, 255],     
              [127, 0, 255],   
              [255, 0, 255],   
              [255, 0, 127]    
            ] %}
            {% set color = colors | random %}
            {{ [color[0], color[1], color[2], 0] }}
          transition: 8
    mode: single
    max_exceeded: silent
